export const Artibonite = {
  "Anse Rouge": ["Sources Chaudes", "l'Arbre"],
  "Desdunes": ["Desdunes"],
  "Dessalines": [
    "Ogé",
    "Villars",
    "Fosse Naboth",
    "Poste Pierrot",
    "Fiéfé",
    "La Croix",
  ],
  "Ennery": [
    "Puilboreau",
    "Passe-Reine",
    "Savane Carrée",
    "Chemin Neuf",
  ],
  "Gonaïves": [
    "de Gonaives",
    "Gonaïves",
    "Petite Rivière de Bayonnais",
    "Pont Tamarin",
    "Bassin",
    "Poteaux",
    "Labranle",
  ],
  "Grande Saline": ["Poteneau"],
  "Gros Morne": [
    "Rivière Blanche",
    "Boucan Richard",
    "Rivière Mancelle",
    "l'Acul",
    "Pendu",
    "Savane Carrée",
    "Moulin",
    "Ravine Gros Morne",
  ],
  "L'Estère": ["Pont de l'Estère"],
  "La Chapelle": ["Bossous", "Martineau"],
  "Marmelade": ["Crète à Pins", "Bassin ou Billier", "Platon"],
  "Petite Rivière de l'Artibonite": [
    "Savane à Roche",
    "Labady",
    "Bas Coursin I",
    "Bas Coursin II",
    "Pérodin",
    "Médor",
  ],
  "Saint Marc": [
    "Déluge",
    "de Saint Marc",
    "Bocozelle",
    "Charrette",
    "Bois Neuf",
    "Goyavier",
    "Lalouère",
    "Bocozelle", // duplicates cleaned later
    "Charrette",
  ],
  "Saint Michel de l' Attalaye": [
    "l'Attalaye",
    "Platana",
    "Bas de Sault",
    "Camathe",
    "Lalomas",
    "l'Ermite",
    "Lacedras",
    "Mamont",
  ],
  "St Marc": ["/St Marc"], // Possibly duplicate of Saint Marc
  "Terre Neuve": ["Bois Neuf", "Doland", "Lagon"],
  "Verrettes": [
    "Desarmes",
    "Guillaume Mogé",
    "Liancourt",
    "Bastien",
    "Belanger",
    "Terre Natte",
  ],
};
