export const GrandAnse: { [commune: string]: string[] } = {
  "Abricots": ["Balisiers", "Anse du Clerc", "Danglise", "La Seringue"],
  "Anse d'Hainault": ["Grandoit", "Bourdon", "Ilet à Joseph", "Mandou"],
  "Beaumont": ["Beaumont"],
  "Bonbon": ["de Désormeau"],
  "Chambellan": ["Dejean", "Boucan"],
  "Corail": ["Duquillon", "Fond d'Icaque", "Champy", "Mouline", "Chardonette"],
  "Dame Marie": [
    "Petite Rivière",
    "Désormeau",
    "Bariadelle",
    "Dallier",
    "Baliverne",
  ],
  "Jeremie": [
    "de Jeremie",
    "Haute Voldrogue",
    "Marfranc",
    "de Jérémie",
    "Fonds Rouge Torberck",
    "Fonds Rouge Dahere",
    "Basse Voldrogue",
    "Haute Voldrogue",
    "Haute Guinaudée",
    "Basse Guinaudée",
    "Ravine à Charles",
    "Iles Blanches",
  ],
  "Jérémie": [
    "Haute Voldrogue",
    "Marfranc",
    "de Jérémie",
    "Fonds Rouge Torberck",
    "Fonds Rouge Dahere",
    "Basse Voldrogue",
    "Haute Voldrogue",
    "Haute Guinaudée",
    "Basse Guinaudée",
    "Ravine à Charles",
    "Iles Blanches",
  ],
  "Les Irois": ["Carcasse", "Matador", "Belair"],
  "Moron": ["Anotte", "L'Assise ou Chameau"],
  "Pestel": [
    "Espère",
    "Bernagousse",
    "Espère",
    "Jean Belune",
    "Tozia",
    "Duchity",
  ],
  "Roseaux": ["Les Gomiers", "Carrefour Charles", "Fond Cochon", "Grand Vincent"],
};
