export const Nord: { [commune: string]: string[] } = {
  "Acul du Nord": [
    "Soufrière",
    "Camp Louise",
    "Bas de l'Acul",
    "Mornet",
    "Grande Ravine",
    "Coupe à David",
  ],
  "Bahon": ["Bailly", "Bois Pin", "Montagne Noire"],
  "Bas Limbé": ["Petit Howard", "Garde Champètre"],
  "Borgne": [
    "Petit Bourg de Borgne",
    "Côtes de Fer",
    "Margot",
    "Boucan Michel",
    "Trou d'Enfer",
    "Champagne",
    "Molas",
  ],
  "Cap-Haïtien": [
    "ier de Petit Anse",
    "Petite Anse",
    "du Cap_Haitien",
    "Haut du Cap",
    "Bande du Nord",
  ],
  "Dondon": [
    "Laguille",
    "Brostage",
    "Bassin Caïman",
    "Matador",
    "Haut du Trou",
  ],
  "Grande Rivière du Nord": [
    "Cormiers",
    "Grand Gilles",
    "Solon",
    "Caracol",
    "Gambade",
    "Joli Trou",
  ],
  "La Victoire": ["La Victoire"],
  "Limbé": [
    "Camp Coq",
    "Ravine Desroches",
    "Haut Limbé",
    "Chabotte",
    "Ilot à Corne",
  ],
  "Limonade": ["Roucou", "Bois de Lance"],
  "Milot": ["Genipailler", "Bonet à l'Evèque", "Perches de Bonet"],
  "Pignon": ["La Belle Mère"],
  "Pilate": [
    "Ballon",
    "Baudin",
    "Ravine Trompette",
    "Joly",
    "Dubourg",
    "Piment",
    "Rivière Laporte",
    "Margot",
  ],
  "Plaine du Nord": ["Basse Plaine", "Morne Rouge", "Bassin Diamant"],
  "Plaisance": [
    "Bassin",
    "Colline Gobert",
    "Champagne",
    "Haut Martineau",
    "Mapou",
    "La Trouble",
    "La Ville",
    "Grande Rivière",
  ],
  "Port Margot": [
    "Bas Quartier",
    "Bras Gauche",
    "Bas Petit Borgne",
    "Grande Plaine",
    "Corail",
    "Haut Petit Borgne",
  ],
  "Quartier Morin": ["Morne Pelé", "Basse Plaine"],
  "Ranquitte": ["Bac à Soude", "Cracaraille"],
  "Saint Raphaël": ["San-Yago", "Bois Neuf", "Mathurin", "Bouyaha"],
};
