export const Ouest = {
  "Anse à Galets": [
    "de l'Anse à Galets",
    "Palma",
    "Petite Source",
    "Grande Source",
    "Grand Lagon",
    "Sect. Picmy",
    "Sect. Petit Anse",
  ],
  "Arcahaie": [
    "ier de Saintard",
    "de l'Arcahaie",
    "Sect. Des Vases",
    "Délices",
    "Matheux",
    "Sect. Fonds Baptiste",
    "Sect. Montrouis",
  ],
  "Cabaret": [
    "Ville de Cabaret",
    "Boucassin",
    "Fonds des Blancs",
    "Sect. Source-Matelas",
  ],
  "Carrefour": [
    "Ville de Carrefour",
    "Sect. Morne Chandelle",
    "Sect. Platon Dufrene",
    "Sect. Taifer",
    "Sect. Procy",
    "Sect. Coupeau",
    "Sect. Bouvier",
    "Sect. Lavalle",
    "Sect. Berly",
    "Sect. Bizoton",
    "Sect. Thor",
    "Sect. Rivière Froide",
    "Sect. Malanga",
    "Sect. Corail Thor",
  ],
  "Cité Soleil": ["Cite Soleil", "Varreux"],
  "Cornillon": [
    "Cornillon",
    "Plaine Céleste",
    "Boucan Bois Pin",
    "Génipailler",
  ],
  "Croix_des_Bouquets": [
    "Ville de Croix des Bouquets",
    "Des Varreux",
    "Sect. Petit Bois",
    "Sect. Belle Fontaine",
    "Belle Fontaine",
    "Sect. des Crochus",
    "des Orangers",
  ],
  "Delmas": [
    "Ville De Delmas",
    "Delmas",
    "Varreux",
  ],
  "Fonds-Verrettes": ["Sect. Fonds-Verrettes"],
  "Ganthier": [
    "ier  Fond Parisien",
    "Ganthier",
    "Galette Chambon",
    "Balan",
    "Sect. Fond Parisien",
    "Sect. Pays Pourri",
    "Sect. Mare Roseaux",
  ],
  "Grand_Goave": [
    "Grand_Goave",
    "Sect. Tête-à-Boeuf",
    "Sect. Moussambé",
    "Sect. Grande Colline",
    "Sect. Gérard",
  ],
  "Gressier": [
    "Ville de Gressier",
    "Morne Bateau",
    "Sect. Morne Chandelle",
    "Sect. Petit Boucan",
  ],
  "Kenscoff": [
    "de Kenscoff",
    "Sect. Nouvelle Tourraine",
    "Bongars",
    "Sourcailles",
    "Sect. Belle Fontaine",
    "Sect. Grand Fond",
  ],
  "Léogane": [
    "Quartier de Trouin",
    "Léogane",
    "Dessources",
    "Petite Rivière",
    "Grande Rivière",
    "Grande Rivère",
    "Orangers",
    "Sect. Parques",
    "Sect. Beausejour",
    "Sect. Citronniers",
    "Sect. Fond d'Oie",
    "Sect. Gros Morne",
    "Sect. Cormiers",
    "Sect. Petit Harpon",
    "Sect. Fond Arabie",
    "Sect. Trou Canari",
  ],
  "Pétion_Ville": [
    "Quartier Thomassin",
    "Bellevue Chardonnières",
    "Ville de Pétion Ville",
    "Sect. Montagne Noire",
    "Sect. Aux Cadets",
    "Pétion_Ville",
    "Sect. Etang du Jonc",
    "Sect. Bellevue La Montagne",
    "Sect. Bellevue Chardonnière",
  ],
  "Petit Goave": [
    "ier de Vialet",
    "de Petit Goave",
    "Sect. Bino(Première Plaine)",
    "Sect.Delatre(2ème Plaine)",
    "Sect. Trou Chouchou",
    "Sect. Trou Canari",
    "Sect. Des Platons",
    "Sect. Des Palmes",
    "Sect. Ravine Sèche",
    "Ravine Sèche",
    "Sect. Des Fourques",
  ],
  "Pointe à Raquette": [
    "Ville de Pointe à Raquette",
    "Sect. La Source",
    "Sect. Grand Vide",
    "Sect. Trou Louis",
    "Sect. Pointe à Raquette",
    "Sect. Gros Mangle",
  ],
  "Port_au_Prince": [
    "de Port_au_Prince",
    "Morne l'Hôpital",
    "Turgeau",
    "Martissant",
  ],
  "Tabarre": [
    "Tabarre",
    "Quartier de Croix des Missions",
  ],
  "Thomazeau": [
    "Thomazeau",
    "Grande Plaine",
    "Sect. des Crochus",
    "Sect. Trou d'Eau",
  ],
};