export const SudEst: { [commune: string]: string[] } = {
  "Anse à Pitre": ["Boucan Guillaume", "Bois d'Orme"],
  "Bainet": [
    "Bas de Grandou",
    "Brésilienne",
    "Trou Mahot",
    "Haut Grandou",
    "Bas de Lacroix",
    "Bras Gauche",
    "Oranger",
    "Bas des Gris Gris",
  ],
  "Belle Anse": [
    "Mapou",
    "Bel Air",
    "Baie d'Orange",
    "Mabriole",
    "Callumette",
    "Corail Lamothe",
    "Pichon",
  ],
  "Cayes Jacmel": ["Gaillard", "Ravine Normande", "Haut Cap Rouge"],
  "Côtes de Fer": [
    "Jamais Vu",
    "Gris Gris",
    "Labiche",
    "Bras Gauche",
    "Amazones",
    "Boucan Bélier",
  ],
  "Grand Gosier": ["Colline des Chaines"],
  "Jacmel": [
    "Quartier de Marbial",
    "Jacmel",
    "Ville de Jacmel",
    "Bas Cap-Rouge",
    "Sect. Bas Cap Rouge",
    "Sect. Fond Melon (Selle)",
    "Sect. Cochon Gras",
    "Sect. La Gosseline",
    "Sect. Marbial",
    "Sect. Montagne la Voute",
    "Sect. Grande Rivière de Jacmel",
    "Sect. Bas Coq Chante",
    "Sect. Haut Coq qui Chante",
    "Morne à Bruler",
    "Sect. La Vanneau",
    "Sect. La Montagne",
    "Fond Melon",
  ],
  "La Vallée": ["La Vallée", "La Vallée"],
  "Marigot": [
    "Fond Jean Noel",
    "Savane Dubois",
    "Corail Soult",
    "Grande Rivière Fesles",
    "Macary",
  ],
  "Thiotte": ["Thiotte", "Pot de Chambre"],
};
