export const Sude: { [commune: string]: string[] } = {
  "Aquin": [
    "Fond des Blancs",
    "Bellevue",
    "Macéan",
    "Brodequin",
    "La Colline",
    "Flamands",
    "Mare à Coiffe",
    "Guirand",
    "Frangipane",
    "Colline à Mongons",
  ],
  "Arniquet": ["Arniquet"],
  "Camp-Perrin": ["Camp-Perrin", "Champlois", "Tibi-Davesac"],
  "Cavaillon": ["Martineau", "Boileau", "Gros Marin"],
  "Chantal": ["Melonière", "Fonds Palmiste", "Carrefour Canon"],
  "Chardonnières": ["Randel", "bony", "Déjoie"],
  "Côteaux": ["des Pas", "Condé", "Quentin"],
  "Ile à Vache": ["Ile à Vache"],
  "Les Anglais": ["Cosse", "Vérone", "Edelin"],
  "Les Cayes": [
    "Laurent",
    "Bourdet",
    "des Cayes",
    "Les Cayes",
    "Fonfrède",
    "Laborde",
    "Mercy",
    "Dory",
    "Melon",
    "Boulmier",
  ],
  "Maniche": ["Maniche"],
  "Port-à-Piment": ["Paricot", "Balais"],
  "Port-Salut": ["Dumont", "Barbois", "Lazare", "Anse à Drick"],
  "Roche-à-Bâteau": ["Beaulieu", "Renaudin", "Beauclos"],
  "Saint Jean du Sud": ["Trichet", "Tapion", "Débouchette"],
  "Saint Louis du Sud": [
    "Baie Dumesle",
    "Grand Fonds",
    "Grenodière",
    "Zanglais",
    "Sucrerie Henri",
    "Solon",
    "Cherette",
    "Corail Henri",
  ],
  "Tiburon": ["Dalmette", "Blacktote", "Nan Sevré", "Loby"],
  "Torbeck": ["Moreau", "Solon", "Bourry", "Bérault"],
};
